{
  config,
  lib,
  ...
}: let
  # Split domain: handles federate as @user@foxsnuggl.es (LOCAL_DOMAIN),
  # while the service itself is served from social.foxsnuggl.es (WEB_DOMAIN).
  federationDomain = "foxsnuggl.es";
  webDomain = "social.foxsnuggl.es";
  streamingProcesses = 1;
in {
  services.mastodon = {
    enable = true;

    # LOCAL_DOMAIN — part of the handle, permanent, drives federation.
    localDomain = federationDomain;

    # WEB_DOMAIN — where the app is actually served. The module has no
    # dedicated option, so it goes in via the environment escape hatch.
    extraConfig.WEB_DOMAIN = webDomain;

    # We serve two vhosts (web domain + federation-domain redirects)
    # ourselves, so the module's single-domain nginx is disabled.
    configureNginx = false;

    streamingProcesses = streamingProcesses;

    # use the shared postgres instance configured in postgres.nix
    database = {
      createLocally = false;
      host = "/run/postgresql";
      name = "mastodon";
      user = "mastodon";
    };

    # redis is provisioned locally by the module (services.redis.servers.mastodon)

    smtp = {
      createLocally = true;
      fromAddress = "mastodon@${webDomain}";
    };
  };

  # Streaming upstream — mirrors what the module builds under configureNginx.
  services.nginx.upstreams.mastodon-streaming = {
    extraConfig = "least_conn;";
    servers = builtins.listToAttrs (
      map (i: {
        name = "unix:/run/mastodon-streaming/streaming-${toString i}.socket";
        value = {};
      }) (lib.range 1 streamingProcesses)
    );
  };

  # WEB_DOMAIN: the actual application (mirrors the module's vhost).
  services.nginx.virtualHosts.${webDomain} = {
    root = "${config.services.mastodon.package}/public/";
    forceSSL = true;
    enableACME = true;

    extraConfig = ''
      client_max_body_size 100m;
    '';

    locations."/system/".alias = "/var/lib/mastodon/public-system/";

    locations."/" = {
      tryFiles = "$uri @proxy";
    };

    locations."@proxy" = {
      proxyPass = "http://unix:/run/mastodon-web/web.socket";
      proxyWebsockets = true;
      recommendedProxySettings = true;
    };

    locations."/api/v1/streaming" = {
      proxyPass = "http://mastodon-streaming";
      proxyWebsockets = true;
      recommendedProxySettings = true;
    };
  };

  # LOCAL_DOMAIN: only redirects identity-discovery endpoints to WEB_DOMAIN.
  # https://docs.joinmastodon.org/admin/config/#web_domain
  services.nginx.virtualHosts.${federationDomain} = {
    forceSSL = true;
    enableACME = true;
    locations."/.well-known/host-meta".return = "301 https://${webDomain}$request_uri";
    locations."/.well-known/webfinger".return = "301 https://${webDomain}$request_uri";
    locations."/.well-known/nodeinfo".return = "301 https://${webDomain}$request_uri";
  };

  # Secrets (secret_key_base, otp_secret, vapid keys) are auto-generated by
  # the module on first start. Registrations are managed via `tootctl`.
}
